#!/bin/sh

set -ex

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

APP_NAME="_APP_NAME_"
OUTPUT="/etc/${APP_NAME}/conf.d/smtp"

# source debconf library
. /usr/share/debconf/confmodule

urlencode() {
  # urlencode <string>
  local length="${#1}"
  for (( i = 0; i < length; i++ )); do
    local c="${1:i:1}"
    case $c in
      [a-zA-Z0-9.~_-]) printf "$c" ;;
      *) printf '%%%02X' "'$c"
    esac
  done
}

urldecode() {
  # urldecode <string>
  local url_encoded="${1//+/ }"
  printf '%b' "${url_encoded//%/\x}"
}

case "$1" in

  configure)
    tmpfile=$(mktemp)

    db_get ${APP_NAME}/smtp/method
    email_delivery_method="$RET"

    db_get ${APP_NAME}/smtp/host || true
    smtp_host="$RET"
    db_get ${APP_NAME}/smtp/port || true
    smtp_port="$RET"
    db_get ${APP_NAME}/smtp/username || true
    smtp_username="$RET"
    db_get ${APP_NAME}/smtp/password || true
    smtp_password="$RET"
    db_get ${APP_NAME}/smtp/domain || true
    smtp_domain="$RET"

    echo "export EMAIL_DELIVERY_METHOD=\"${email_delivery_method}\"" > "$tmpfile"
    if [ "$email_delivery_method" = "smtp" ]; then
      echo "export SMTP_HOST=\"${smtp_host}\"" >> "$tmpfile"
      echo "export SMTP_PORT=\"${smtp_port}\"" >> "$tmpfile"
      echo "export SMTP_USERNAME=\"${smtp_username}\"" >> "$tmpfile"
      echo "export SMTP_PASSWORD=\"${smtp_password}\"" >> "$tmpfile"
      echo "export SMTP_DOMAIN=\"${smtp_domain}\"" >> "$tmpfile"
      # generate SMTP_URL, urlencode username and password
      smtp_url="smtp://$(urlencode "${smtp_username}"):$(urlencode "${smtp_password}")@${smtp_host}:${smtp_port}/${smtp_domain}"
      echo "export SMTP_URL=\"${smtp_url}\"" >> "$tmpfile"
    fi

    mv -f "$tmpfile" "$OUTPUT"
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

